apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backend
  labels:
    app: data-retrieval
    component: backend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
  source:
    type: Git
    git:
      uri: https://github.com/bodarajeshkumar/idvalidation
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: openshift/backend.Dockerfile
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: github-webhook-secret

# Made with Bob
