apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend
  labels:
    app: data-retrieval
    component: frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
  source:
    type: Git
    git:
      uri: https://github.com/bodarajeshkumar/idvalidation
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: openshift/frontend.Dockerfile
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: github-webhook-secret

# Made with Bob
