---
apiVersion: v1
kind: Secret
metadata:
  name: cloudant-credentials
  labels:
    app: data-retrieval
type: Opaque
stringData:
  api-base-url: "REPLACE_WITH_YOUR_API_BASE_URL"
  api-key: "REPLACE_WITH_YOUR_API_KEY"
  api-password: "REPLACE_WITH_YOUR_API_PASSWORD"

# Made with Bob
